In [1]:
# Importing necessary libraries for data manipulation and visualization

import pandas as pd

In [2]:
# Reading the CSV file containing student attitude and behavior data into a pandas DataFrame
df = pd.read_csv('Student Attitude and Behavior.csv')

In [3]:
df.head()

,Certification Course,Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,willingness to pursue a career based on their degree,social medai & video,Travelling Time,Stress Level,Financial Status,part-time job
0,No,Male,BCA,100.0,58.0,79.0,64.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,71.0,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 19 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   Certification Course                                    235 non-null    object
 1   Gender                                                  235 non-null    object
 2   Department                                              235 non-null    object
 3   Height(CM)                                              235 non-null    float64
 4   Weight(KG)                                              235 non-null    float64
 5   10th Mark                                               235 non-null    float64
 6   12th Mark                                               235 non-null    float64
 7   college mark                                            235 non-null    float64
 8   hobbies                                                 235 non-null    object
 9   daily studing time                                      235 non-null    object
 10  prefer to study in                                      235 non-null    object
 11  salary expectation                                      235 non-null    int64
 12  Do you like your degree?                                235 non-null    object
 13  willingness to pursue a career based on their degree    235 non-null    object
 14  social medai & video                                    235 non-null    object
 15  Travelling Time                                         235 non-null    object
 16  Stress Level                                            235 non-null    object
 17  Financial Status                                        235 non-null    object
 18  part-time job                                           235 non-null    object
dtypes: float64(5), int64(1), object(13)
memory usage: 35.0+ KB

In [5]:
# Dropping specified columns and rows with missing values from the DataFrame

dropColumns = ['Gender', 'Department', 'Height(CM)', 'Weight(KG)', 'hobbies', 'salary expectation', 'social medai & video', 'Financial Status','prefer to study in']
df.drop(dropColumns, axis=1, inplace=True)

df.dropna(axis=0,inplace=True)

In [6]:
uniqueDST = df['daily studing time'].unique()
print(uniqueDST)

uniqueTT = df['Travelling Time '].unique()
print(uniqueTT)

uniqueSL = df['Stress Level '].unique()
print(uniqueSL)

['0 - 30 minute' '30 - 60 minute' '1 - 2 Hour' '2 - 3 hour' '3 - 4 hour'
 'More Than 4 hour']
['30 - 60 minutes' '0 - 30 minutes' '1 - 1.30 hour' '2 - 2.30 hour'
 '1.30 - 2 hour' 'more than 3 hour' '2.30 - 3 hour']
['Bad' 'Awful' 'Good' 'fabulous']

In [7]:
df.replace('No',0,inplace=True)
df.replace('Yes', 1, inplace=True)

df['daily studing time'].replace('0 - 30 minute',0,inplace=True)
df['daily studing time'].replace('30 - 60 minute',1,inplace=True)
df['daily studing time'].replace('1 - 2 Hour',2,inplace=True)
df['daily studing time'].replace('2 - 3 hour',3,inplace=True)
df['daily studing time'].replace('3 - 4 hour',4,inplace=True)
df['daily studing time'].replace('More Than 4 hour',5,inplace=True)

df['Travelling Time '].replace('0 - 30 minutes',0,inplace=True)
df['Travelling Time '].replace('30 - 60 minutes',1,inplace=True)
df['Travelling Time '].replace('1 - 1.30 hour',2,inplace=True)
df['Travelling Time '].replace('1.30 - 2 hour',3,inplace=True)
df['Travelling Time '].replace('2 - 2.30 hour',4,inplace=True)
df['Travelling Time '].replace('2.30 - 3 hour',5,inplace=True)
df['Travelling Time '].replace('more than 3 hour',6,inplace=True)

df['Stress Level '].replace('Bad',0,inplace=True)
df['Stress Level '].replace('Awful',1,inplace=True)
df['Stress Level '].replace('Good',2,inplace=True)
df['Stress Level '].replace('fabulous',3,inplace=True)

df['willingness to pursue a career based on their degree  '] = df['willingness to pursue a career based on their degree  '].str.replace('%', '').astype(float)

C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('Yes', 1, inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('0 - 30 minute',0,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('30 - 60 minute',1,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('1 - 2 Hour',2,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('2 - 3 hour',3,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('3 - 4 hour',4,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['daily studing time'].replace('More Than 4 hour',5,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['daily studing time'].replace('More Than 4 hour',5,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('0 - 30 minutes',0,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('30 - 60 minutes',1,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('1 - 1.30 hour',2,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('1.30 - 2 hour',3,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('2 - 2.30 hour',4,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('2.30 - 3 hour',5,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Travelling Time '].replace('more than 3 hour',6,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:17: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Travelling Time '].replace('more than 3 hour',6,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stress Level '].replace('Bad',0,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stress Level '].replace('Awful',1,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stress Level '].replace('Good',2,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Stress Level '].replace('fabulous',3,inplace=True)
C:\Users\Rupin\AppData\Local\Temp\ipykernel_27072\344123731.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Stress Level '].replace('fabulous',3,inplace=True)

In [8]:
df.head()

,Certification Course,10th Mark,12th Mark,college mark,daily studing time,Do you like your degree?,willingness to pursue a career based on their degree,Travelling Time,Stress Level,part-time job
0,0,79.0,64.0,80.0,0,0,50.0,1,0,0
1,0,70.0,80.0,70.0,1,1,75.0,0,0,0
2,1,71.0,61.0,55.0,2,1,50.0,1,1,0
3,1,70.0,59.0,58.0,2,0,50.0,0,0,0
4,0,40.0,65.0,30.0,1,1,25.0,1,2,0

In [9]:
# Prepare the Dataset

X,y=df.drop('willingness to pursue a career based on their degree  ',axis=1), df['willingness to pursue a career based on their degree  '].values

In [10]:
# Split Data into Training and Testing Sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=69)

In [46]:
from sklearn.svm import SVC
model = SVC(kernel='rbf')
model.fit(X_train, y_train)

0.5211267605633803

In [36]:
predictions = model.predict(X_test)
model.score(X_test, y_test)

0.4084507042253521

In [13]:
# Starting our Web Service

from flask import Flask, request
app = Flask(__name__)

In [14]:
@app.get("/career/sample")
def get_sample():
    # Return the first row of the DataFrame as JSON after dropping the specified column.
    return df.drop('willingness to pursue a career based on their degree  ',axis=1).iloc[0].to_json(orient="index")

In [15]:
@app.get("/career/explain")
def explain_sample():
    return (
        "Explanation: \n\n"
        "The sample at '/career/sample' is a JSON representation of the first row of the DataFrame after removing the 'willingness to pursue a career based on their degree' column. It illustrates the data structure and content post-column removal.\n\n"
        "The algorithm predicts how students' attitudes and behaviors impact their academic success and school involvement.\n\n"
        "Column Details:\n"
        "1. Certification Course: 0 for No, 1 for Yes.\n"
        "2. 10th Mark: Float value representing percentage or grade.\n"
        "3. 12th Mark: Float value representing percentage or grade.\n"
        "4. College Mark: Float value representing percentage or grade.\n"
        "5. Daily Studying Time: 0 for 0 - 30 minutes, 1 for 30 - 60 minutes, 2 for 1 - 2 hours, 3 for 2 - 3 hours, 4 for 3 - 4 hours, 5 for More Than 4 hours.\n"
        "6. Do You Like Your Degree?: 0 for No, 1 for Yes.\n"
        "7. Travelling Time: 0 for 0 - 30 minutes, 1 for 30 - 60 minutes, 2 for 1 - 1.30 hours, 3 for 1.30 - 2 hours, 4 for 2 - 2.30 hours, 5 for 2.30 - 3 hours, 6 for More than 3 hours.\n"
        "8. Stress Level: 0 for Bad, 1 for Awful, 2 for Good, 3 for Fabulous.\n"
        "9. Part-Time Job: 0 for No, 1 for Yes.\n\n"
        "URL: http://127.0.0.1:5000/career/evaluate\n\n"
        "Description: Evaluate data by submitting JSON formatted data similar to the sample entry. The response will be a float indicating the predicted willingness to learn based on the provided data."
    )

In [16]:
@app.post("/career/evaluate")
def test_sample():
    if request.is_json:
        # Convert the JSON request body to a DataFrame and make a prediction using the model.
        df = request.get_json()
        dfTest = pd.DataFrame([df])
        result = model.predict(dfTest)
        return '{}'.format(result[0])
    return {"error": "Request must be JSON"}

In [17]:
# Start the Flask application server.
if __name__ == '__main__':
    app.run()

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit